### ISSUE TITLE
Write a basic test for LongestStringMatching

### ISSUE THREAD

**Issue by jacksonllee** [jacksonllee/wordseg#1]
Write a basic test for the `LongestStringMatching` model class. Changes needed:

* Add a new file `wordseg/tests/test_longest_string_matching.py` (so this new `test_longest_string_matching.py` file will be in the same directory as the already existing `test_version.py`).
* In `test_longest_string_matching.py` just created, add a function called `test_basic`. In `test_basic`, copy the example for how to use `LongestStringMatching` from the [README code snippet](https://github.com/jacksonllee/wordseg/blob/d1cadd9aadbe5f440f773100d1b9c6589f2d985c/README.md#usage) to this `test_basic` function. At the end of `test_basic`, we should `assert` that `list(model.predict(["thatisadog", "thisisnotacat"]))` is equal to (by `==`) the expected value.
* Add an entry to `CHANGELOG.md`.

**Comment by fakhrip** [comment]
Hey can i work on this one ? @jacksonllee

**Comment by jacksonllee** [comment]
@fakhrip Yes, a pull request would be welcomed!

**Comment by xcyraxx** [comment]
hwy is this still open?
